[project]
name = "adl-bnn-textgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "posteriors>=0.1.1",
    "torch>=2.8.0",
]
